### ISSUE TITLE
File chooser can't change drive letter on Windows

### ISSUE THREAD

**Issue by tar-viturawong-frequenz** [CIB-Mango-Tree/mango-tango-cli#1]
The current implementation of the file browser prompt only allows navigation up to the top level of a directory tree, which is fine in a Linux filesystem where everything can be accessible from the root path `/`. On Windows, every drive is considered be its own directory tree with its own root path (`C:\`, `D:\`, etc), and there's no representation that can represent the super-root where all drives are listed. If the CLI is started in the current working directory that's in a different drive from where the data lives, the user cannot choose that file.

Wanted: design and implement an interaction that allows the user to change the drive letter.

**Comment by soul-codes** [comment]
This was fixed with #8.
