### ISSUE TITLE
[BUG] hashtags outputs to export fails when choosing CSV output (badly formated export path, attempts saving as parquet file)

### ISSUE THREAD

**Issue by KristijanArmeni** [CIB-Mango-Tree/mango-tango-cli#4]
This is very likely a bug in [my own current hashtag branch](https://github.com/KristijanArmeni/mango-tango-cli/tree/hashtags) rather than the CLI bug, but it is hard to trace down because the CLI doesn't print the error trace stack (at least in my local testing).

## What happened

On my hashtags branch, I run:
```bash
python -m mangotango
```

I walk through the GUI (see screenshots), and get the error upon exporting (see the last screenshot). There I get stuck troubleshooting, but likely my interface is missing something in analyzer declaration such that the CLI storage export functionality constructs a bad export path.

It seems the CLI will accept my [hashtags.main()](https://github.com/KristijanArmeni/mango-tango-cli/blob/3bb214ab921722ed755f031014e60b50b39146a4/analyzers/hashtag/main.py#L35), offer me to export the outputs as CSV and will then choke trying to export it as parquet file.

A confusing thing is also that it attempts to export as parquet, but I selected the CSV option.

## Expected behavior
Export to .csv via Polars or so (and possibly print output preview).

## Error screenshots
![Screenshot 2024-10-18 at 9 34 49 AM](https://github.com/user-attachments/assets/110a6ece-ee87-4f90-b2f4-d00fd8e5c509)
![Screenshot 2024-10-18 at 9 35 20 AM](https://github.com/user-attachments/assets/2751887f-a6b2-4541-b8a9-9024ee1648dc)
![Screenshot 2024-10-18 at 9 35 42 AM](https://github.com/user-attachments/assets/b7ff43c2-62ec-442e-a265-c5d2c1158cd2)

**Comment by soul-codes** [comment]
It appears that the [interface](https://github.com/KristijanArmeni/mango-tango-cli/blob/3bb214ab921722ed755f031014e60b50b39146a4/analyzers/hashtag/interface.py#L42-L49) is declaring a different output ID than that used by the [analyzer](https://github.com/KristijanArmeni/mango-tango-cli/blob/3bb214ab921722ed755f031014e60b50b39146a4/analyzers/hashtag/main.py#L73)

```python
# interface.py: line 8
OUTPUT_GINI = "gini_coef"

# ...

    # interface.py: line 42 
    AnalyzerOutput(
      id=OUTPUT_GINI,
      name="gini_coef_over_time",
      columns=[
        OutputColumn(name=OUTPUT_COL_TIMESPAN, data_type="datetime"),
        OutputColumn(name=OUTPUT_COL_GINI, data_type="float"),
      ]
    )
```

```python
    # main.py: line 73
    return {"gini_coef_over_time": df_agg}
```

The actual analyzer function is returning the main dataframe in the output ID `gini_coef_over_time` but the schema defines the output `gini_coef`. It appears that this is a mix up between human-readable name (which is defined using `name`).

As a result, the analyzer's output gets saved in a different filename than the main CLI can find later.

To fix, try something like this:

```diff
# main.py: line 3
-from .interface import (COL_AUTHOR_ID, COL_TIME, COL_HASHTAGS)
+from .interface import (COL_AUTHOR_ID, COL_TIME, COL_HASHTAGS, OUTPUT_GINI)


      # main.py: line 73
-     return {"gini_coef_over_time": df_agg}
+     return {OUTPUT_GINI: df_agg}
```

With this, I managed to get your branch to run:

![image](https://github.com/user-attachments/assets/c77c613e-0566-4d98-b385-9c12a469360e)

![image](https://github.com/user-attachments/assets/03f43e42-929e-4d48-8608-d4018194f6af)

You should also then correct the human readable name:

```diff
     # interface.py: line 42
     AnalyzerOutput(
       id=OUTPUT_GINI,
       id=OUTPUT_GINI,
-      name="gini_coef_over_time",
+      name="Gini coefficient over time",
       columns=[
         OutputColumn(name=OUTPUT_COL_TIMESPAN, data_type="datetime"),
         OutputColumn(name=OUTPUT_COL_GINI, data_type="float"),
       ]
     )
```

This highlights a couple of system-level issues here:
- The schema specification itself is a inconsistent this way, `name` is a programmatic name for inside input column declarations, but it's human-readable name in output table declarations. 🤦 For this, let's have your test merged in first and we can refactor the schema itself.
- It would be nice for the core to validate the return value against the output table. 

Closing as the mystery is solved and determined not to be a bug.
